# Generated by Django 5.0.1 on 2024-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langinf',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='langinf',
            name='slug',
            field=models.SlugField(max_length=2),
        ),
    ]
